apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterfan-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterfan-master
  template:
    metadata:
      labels:
        app: clusterfan-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: kmaster
      containers:
      - name: clusterfan-master
        image: nousefreak/clusterfan:0.0.4
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          privileged: true
          allowPrivilegeEscalation: true
        env:
        - name: CLUSTERFAN_ISMASTER
          value: "true"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 20Mi
            cpu: 50m
          requests:
            cpu: 30m
            memory: 20Mi