name: docker-release

on:
  push:
    branches:
      - master

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Dump Version
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch
        id: bumpr

      - name: Build and publish image
        uses: stenic/docker_buildx@master
        with:
          publish: true
          imageName: nousefreak/clusterfan
          tag: ${{ steps.bumpr.outputs.next_version }}
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_TOKEN }}
